import { Ri24HoursFill, RiNurseFill, RiHeartFill, RiHome2Fill, RiGroupFill, RiHospitalFill, RiUserHeartFill, RiMentalHealthLine } from "react-icons/ri";
import {
  MdHandshake, MdSelfImprovement, MdHealthAndSafety, MdMedicalServices, MdLocalHospital,
  MdFamilyRestroom, MdAccessible, MdHome, MdPeople, MdPhone, MdLocationOn, MdSchedule,
  MdStar, MdVolunteerActivism, MdSupportAgent, MdPsychology, MdElderly, MdNightShelter,
  MdSupervisedUserCircle, MdPersonPin,
} from "react-icons/md";
import { FiHeart, FiActivity, FiPhone, FiMapPin, FiClock, FiUser, FiUsers, FiShield, FiAward, FiCheckCircle, FiHome, FiCalendar, FiStar } from "react-icons/fi";
import { FaStar, FaHeart, FaWheelchair, FaHospital, FaBed, FaHandHoldingHeart, FaStethoscope } from "react-icons/fa";
import { BsHouseFill, BsPersonFill, BsPeopleFill, BsHeartFill, BsShieldFill, BsCalendarCheck } from "react-icons/bs";
import { TbWorld, TbStethoscope, TbFirstAidKit } from "react-icons/tb";

export const ICON_REGISTRY = {
  Ri24HoursFill,
  RiNurseFill,
  RiHeartFill,
  RiHome2Fill,
  RiGroupFill,
  RiHospitalFill,
  RiUserHeartFill,
  RiMentalHealthLine,
  MdHandshake,
  MdSelfImprovement,
  MdHealthAndSafety,
  MdMedicalServices,
  MdLocalHospital,
  MdFamilyRestroom,
  MdAccessible,
  MdHome,
  MdPeople,
  MdPhone,
  MdLocationOn,
  MdSchedule,
  MdStar,
  MdVolunteerActivism,
  MdSupportAgent,
  MdPsychology,
  MdElderly,
  MdNightShelter,
  MdSupervisedUserCircle,
  MdPersonPin,
  FiHeart,
  FiActivity,
  FiPhone,
  FiMapPin,
  FiClock,
  FiUser,
  FiUsers,
  FiShield,
  FiAward,
  FiCheckCircle,
  FiHome,
  FiCalendar,
  FiStar,
  FaStar,
  FaHeart,
  FaWheelchair,
  FaHospital,
  FaBed,
  FaHandHoldingHeart,
  FaStethoscope,
  BsHouseFill,
  BsPersonFill,
  BsPeopleFill,
  BsHeartFill,
  BsShieldFill,
  BsCalendarCheck,
  TbWorld,
  TbStethoscope,
  TbFirstAidKit,
};
